name: CI

on:
  push:
    branches:
      - main



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create a test.txt file
        run: touch test.txt
        
      - name: Adding data
        run: echo Hello world > test.txt

      - name: Completed file Creation
        run: echo "Test file created"

      - name: Value of Github workspace
        run: pwd

      - name: List files in github workspace
        run: ls -la $GITHUB_WORKSPACE
      
      - name: List Files
        run: ls -la

      - name: Cat file
        run: cat test.txt
      
      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key

      - name: Transfering File to server
        run: scp -i ssh_key test.txt ${{ secrets.SSH_HOST }}:/home
      
      - name: Copy File
        run: echo "file Copied"
