name: CI

on:
  push:
    branches:
      - main



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create a test.txt file
        run: touch test.txt
        
      - name: Completed file Creation
        run: echo "Test file created"

      - name: Value of Github workspace
        run: echo $GITHUB_WORKSPACE/test.txt

      - name: List files in github workspace
        run: ls -la $GITHUB_WORKSPACE
      
      - name: List Files
        run: ls -la

      - name: Transfering File to server
        run: scp -i ${{ secrets.SSH_PRIVATE_KEY }} $GITHUB_WORKSPACE/test.txt ${{ secrets.SSH_HOST }}:/home
      
      - name: Copy File
        run: echo "file Copied"